title: Tracker Documentation
description: The documentation of the project Tracker
theme: just-the-docs

url: https://TrackER-Corporation/TrackER-Report

aux_links:
  Template Repository: https://github.com/TrackER-Corporation/TrackER-Report
  
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  
mermaid:
  version: "9.1.3"
  
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/just-the-docs/just-the-docs"
    
aux_links_new_tab: false
    
heading_anchors: true

markup / liquid-based content.
footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"

last_edit_timestamp: true 
last_edit_time_format: "%b %e %Y at %I:%M %p" 

gh_edit_link: true 
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" 
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

color_scheme: dark
