title: "Tracker Documentation"
description: "The documentation of the project Tracker"
remote_theme: pmarsceill/just-the-docs
color_scheme: dark

url: https://tracker-corporation.github.io/TrackER-Report/